config/routes.rb
Rails.application.routes.draw do
  get 'genres/index'
  get 'types/index'
  root to: "home#index"

  # get 'home/index'
  get 'about/index'
  get 'anime/index'
  get 'anime/show'
  get 'users/index'
  get 'users/show'

  resources :types, only: [:index]
  resources :genres, only: [:index]

  resources :anime, only: [:index, :show] do
    #movies/search/(:format)
    collection do
      get "search"
    end

    get '/page/:page', action: :index, on: :collection
  end

  resources :users, only: [:index, :show] do
    get '/page/:page', action: :index, on: :collection
  end
end

app/models/anime.rb
class Anime < ApplicationRecord
  paginates_per 10

  has_many :anime_genres
  has_many :genres, through: :anime_genres

  has_many :rates
  has_many :users, through: :rates

  belongs_to :type

  validates :name, presence: true, uniqueness: true
  validates_length_of :name, minimum: 1, maximum: 70, allow_blank: false
end

app/models/anime_genre.rb
class AnimeGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :anime
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :anime_genres
  has_many :animes, through: :anime_genres

  validates :name, presence: true, uniqueness: true
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :anime
  belongs_to :user

  validates :rate, presence: true, :inclusion => { :in => -1..10 }
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :animes

  validates :name, presence: true, uniqueness: true
  validates_length_of :name, minimum: 1, maximum: 50, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rates
  has_many :animes, through: :rates

  validates :name, presence: true, uniqueness: true
  validates_length_of :name, minimum: 1, maximum: 50, allow_blank: false
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/anime_controller.rb
class AnimeController < ApplicationController
  def index
    @animes = Anime.includes(:type).all.order("rating DESC").page params[:page]
  end

  def show
    @anime = Anime.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    search_type     = params[:type]
    #debugger.log(wildcard_search)

    if search_type != ""
      @totals = Anime.where("name LIKE ?", wildcard_search).where(type_id: search_type)
      @animes = Anime.where("name LIKE ?", wildcard_search).where(type_id: search_type).order("rating DESC").page params[:page]
    else
      @totals = Anime.where("name LIKE ?", wildcard_search)
      @animes = Anime.where("name LIKE ?", wildcard_search).order("rating DESC").page params[:page]
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.includes(:animes).all.order("name DESC")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @animes = Anime.includes(:type)
                   .order("rating DESC")
                   .limit(10)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.includes(:animes).all.order("name DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:rates).all.page params[:page]
  end

  def show
    @user = User.joins(:rates).where(id: params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/anime_helper.rb
module AnimeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Anime Rating</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <%= render partial: 'shared/header' %>
    <%= yield %>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href=<%= root_path %> class="nav-link px-2 text-muted">Home</a></li>
    <li class="nav-item"><a href=<%= about_index_path %> class="nav-link px-2 text-muted">About</a></li>
    <li><a href=<%= anime_index_path %> class="nav-link px-2 text-muted">Animes</a></li>
  </ul>
  <p class="text-center text-muted">© 2022 Jia Hong Ye</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

app/views/shared/_header.html.erb
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href=<%= root_path %> class="nav-link px-2 text-white">Home</a></li>
		      <li><a href=<%= about_index_path %> class="nav-link px-2 text-white">About</a></li>
          <li><a href=<%= anime_index_path %> class="nav-link px-2 text-white">Animes</a></li>
          <li><a href=<%= types_index_path %> class="nav-link px-2 text-white">Types</a></li>
          <li><a href=<%= genres_index_path %> class="nav-link px-2 text-white">Genres</a></li>
          <li><a href=<%= users_index_path %> class="nav-link px-2 text-white">Users</a></li>
        </ul>

        <%= form_with(url: search_anime_index_path, method: :get, local: true) do %>
          <div class="input-group">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search" name="keywords"/>

            <label class="input-group-text" for="searchCategory">Type</label>
            <select id="searchCategory" class="form-control form-control-dark" name="type">
              <option value="">All</option>
              <% Type.all.each do |type| %>
              <option value=<%= type.id %>><%= type.name %></option>
              <% end %>
            </select>

          </div>
        <% end %>

      </div>
    </div>
</header>